# Find the docs at github.com/PokerFacowaty/stash-qmt
API Key: <your API key>
Stash URL: <Stash URL ending in /graphql>
Templates:
  SampleTemplate1:
    - SampleTagName1
    - SampleTagName2
  SampleTemplate2:
    12: TagWithId12
    33: TagWithId33